### ISSUE TITLE
Crew-form

### ISSUE THREAD

**Issue by gottemeyer** [Viva-con-Agua/arise#2]
Users can create and update a Crew. For this feature a view has to be implemented, containing the fields:

-name `string`
-country `string`
-cities `string` (a second and more cities can be added by tapping a `+` button which creates a new input form-field

the country and  city form-fields should contain an Autofill option. Also the fields should be validated like:

-name `required`
-country `required, alpha_dash`
-cities `required, alpha_dash` (+ at least one city has to be given)

The Crew-form is expanded by [Crew-form #3](https://github.com/Viva-con-Agua/arise/issues/3)

**Comment by johannsell** [comment]
Autocomplete: https://developers.google.com/places/web-service/autocomplete?hl=de
