### ISSUE TITLE
Profile page display error (Mobile FF)

### ISSUE THREAD

**Issue by TobiKaestle** [Viva-con-Agua/arise#91]
The profile page of arise is strange when in mobile view with firefox.
Only the last container (Change email, change pass, delete..) is seen correctly.

**Comment by johannsell** [comment]
Okay, first of all, the `VcAColumn` components have currently `min-height: 100%` - that has to be changed to `min-height: auto` for the responsive breakpoints.
After all, the `VcAColumn` components will be visible in FF, but the first `VcABox` is partially hidden. Thus, I have to go on with the search...
